# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'sticky-sessions-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Swift.Json'
  pod 'Alamofire'
  pod 'SwipeCellKit'

  # Pods for sticky-sessions-ios

  target 'sticky-sessions-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sticky-sessions-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
